CREATE TABLE "word" (
  "word_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "word" varchar(16),
  "reading" string(32)
);

CREATE TABLE "definition" (
  "definition_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "definition" text
);

CREATE TABLE "word_definition" (
  "word_id" int NOT NULL,
  "definition_id" int NOT NULL
);

CREATE TABLE "definition_used_words" (
  "definition_id" int NOT NULL,
  "word_id" int NOT NULL
);

ALTER TABLE "word_definition" ADD FOREIGN KEY ("word_id") REFERENCES "word" ("word_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "word_definition" ADD FOREIGN KEY ("definition_id") REFERENCES "definition" ("definition_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "definition_used_words" ADD FOREIGN KEY ("definition_id") REFERENCES "definition" ("definition_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "definition_used_words" ADD FOREIGN KEY ("word_id") REFERENCES "word" ("word_id") DEFERRABLE INITIALLY IMMEDIATE;
