"""empty message

Revision ID: 38e0106b0697
Revises: 89b1d64df278
Create Date: 2026-09-20 17:30:52.526101

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38e0106b0697"
down_revision: str | Sequence[str] | None = "89b1d64df278"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def make_search_key(key: str) -> str:
    to_remove = (
        " !&'()+,-./:;<=>?@〇〈〉《》「」『』【】〔〕・ー＃＆（）＊＋－／＝｜‐"
    )
    res = ""
    i = 0
    while i < len(key):
        if (
            i + 12 < len(key)
            and key[i] == "<"
            and key[i + 1] == "s"
            and key[i + 2] == "u"
            and key[i + 3] == "p"
            and key[i + 4] == ">"
        ):
            i += 12
        elif key[i] in to_remove:
            i += 1
        else:
            res += key[i]
            i += 1
    return res


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dictionary_entries", sa.Column("search_key", sa.String()))
    connection = op.get_bind()
    rows = (
        connection.execute(sa.text("SELECT id, key FROM dictionary_entries"))
        .mappings()
        .all()
    )
    for row in rows:
        search_key = make_search_key(row["key"])
        connection.execute(
            sa.text(
                "UPDATE dictionary_entries SET search_key = :search_key WHERE id = :id"
            ),
            {"id": row["id"], "search_key": search_key},
        )
    op.alter_column("dictionary_entries", "search_key", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dictionary_entries", "search_key")
    # ### end Alembic commands ###
